### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by whesse** [dart-lang/mime#4]
The version pinned in sdk/DEPS is above the last version published to pub and tagged.  Please make a new version and publish.

**Comment by thosakwe** [comment]
Are PR's open?

**Comment by whesse** [comment]
No, there are no PRs currently open.  There have been commits, like making the package strong mode clean, that have landed, and are not available on pub because it hasn't been published.

If you are asking if PRs are accepted, then yes, they are.

**Comment by thosakwe** [comment]
Oh, sorry. I was definitely asking if they were accepted. Should have chosen a different word...

**Comment by devoncarew** [comment]
this issue is stale
