### ISSUE TITLE
improve the detection of mp4 types

### ISSUE THREAD

**Issue by ryanhaining** [dart-lang/mime#86]
The [first 8 bytes in magic_number.dart for `video/mp4` are correct](https://github.com/dart-lang/mime/blob/642c9cec7a17c5751825343b8f476fba2b0902d9/lib/src/magic_number.dart#L117-L124) but the final 4 bytes make it more specific than it needs to be as they refer to the subtype. From a bit of experimenting it looks like dropping the last 4 elements from there (and the mask) would fix this. All the references that I can find list an 8 byte header.

- https://en.wikipedia.org/wiki/List_of_file_signatures
- https://www.file-recovery.com/mp4-signature-format.htm
- https://www.garykessler.net/library/file_sigs.html

**Comment by ivangolubykh** [comment]
How about this article?:
https://www.file-recovery.com/mp4-signature-format.htm
It will be an error if only 8 bytes are left. In fact, you need to check 12 bytes, and at the same time, bytes 9-12 can be in different versions, that is, you need to make several MagicNumbers for the video / mp4 type

**Comment by ivangolubykh** [comment]
If you check only 8 bytes you will get a QuickTime format which is used for both video/mp4 and video/3gpp and many more.
The old code, which is now in the repository, just points to the video/3gpp format [ 0x00, 0x00, 0x00, 0x00, 0x66, 0x74, 0x79, 0x70, 0x33, 0x67, 0x70, 0x35 ] and this is of course wrong.

**Comment by ryanhaining** [comment]
I see, okay yes you're right it would need a lot of specification. The `const` on `initialMagicNumbers` means this would need to be a lot more verbose than it otherwise would, but it definitely needs to be different.

**Comment by ivangolubykh** [comment]
If the current Pull request is not accepted, can I make my own? I would like to contribute to the solution of this problem.
